### ISSUE TITLE
compilation warning

### ISSUE THREAD

**Issue by fbergo** [usnistgov/frvt#1]
In frvt11.h, the lack of a default label in the method

`inline std::ostream& operator<<(std::ostream &s, const ReturnCode &rc)`

causes a compiler warning when it is called:

`c++ -std=c++11 -mavx -Wall -O2 -c trivial.cc -o libtrivial.so`
`c++ -std=c++11 -mavx -Wall -O2 client.cc -L. -ltrivial -o client`
`In file included from client.cc:2:0:`
`frvt11.h: In function ‘std::ostream& FRVT::operator<<(std::ostream&, const FRVT::ReturnCode&)’:`
`frvt11.h:163:1: warning: control reaches end of non-void function [-Wreturn-type]`

**Comment by mlngan** [comment]
Added default statement to ReturnCode output stream operator.
