### ISSUE TITLE
Install required packages for runtime

### ISSUE THREAD

**Issue by mexeniz** [usnistgov/frvt#10]
Is it possible to install dependent packages for runtime and list these packages in ./config directory?
For example, I am implementing with OpenCV and OpenCV requires these packages installed for runtime:
- libjpeg-turbo-devel
- libtiff-devel 
- libdc1394-devel
- eigen3-devel
and etc.

**Comment by mlngan** [comment]
For any software dependencies your algorithm requires, you need to provide them (the libraries themselves) in your submission under the ./lib folder.

**Comment by quocnhat** [comment]
hi @mexeniz, @mlngan 
how did you handle the libraries needed by third-party libraries?
for example: 
set (CMAKE_SHARED_LINKER_FLAGS "-Wl,-rpath,$ORIGIN")
add_library (frvt_11_null_001 SHARED nullimplfrvt11.cpp)
target_link_libraries(frvt_11_null_001 libdc1394.so.22 thirdpartylib2.so ...)
We can submit libdc1394.so.22 in ./lib folder but  libdc1394.so.22 also call to some other libs like: libraw1394.so.0.1 ,... .
How did you handle these cases? Thank you in advance
