### ISSUE TITLE
How many images does search dataset have? 1:N

### ISSUE THREAD

**Issue by LionLion888** [usnistgov/frvt#101]
Hi,

In the 1:N identify project, the enrollment dataset will get 1 million images as input data, if face detection failed, it shall still return a blank template and continue to go through the next enroll image. 

For the search dataset, I'm wondering there would be how many images? In the following picture, the search photo seems to be only one image. (Wanted to make sure it wold be **one person with one image** or **one person with multi images**.)

![image](https://github.com/usnistgov/frvt/assets/133086055/90187b80-9501-41f1-b93e-0ef969a7b301)

**Comment by mlngan** [comment]
The search/probe could be any of the following
1. one image of one person (Function A)
2. multiple images of one person (Function A)
3. one image with multiple people in it (Function B)

**Function A:** 
FRVT::ReturnStatus
    createFaceTemplate(
        const std::vector<FRVT::Image> &faces,
        FRVT::TemplateRole role,
        std::vector<uint8_t> &templ,
        std::vector<FRVT::EyePair> &eyeCoordinates)

**Function B:** 
FRVT::ReturnStatus
    createFaceTemplate(
        const FRVT::Image &image,
        FRVT::TemplateRole role,
        std::vector<std::vector<uint8_t>> &templ,
        std::vector<FRVT::EyePair> &eyeCoordinates)

**Comment by LionLion888** [comment]
Thanks for your reply!

**Comment by paddygr** [comment]
Look at the N values at the top of the columns here:
https://pages.nist.gov/frvt/html/frvt1N.html



From: LionLion888 ***@***.***>
Date: Tuesday, August 8, 2023 at 2:16 AM
To: usnistgov/frvt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [usnistgov/frvt] How many images does search dataset have? 1:N (Issue #101)

Thanks for your reply!
