### ISSUE TITLE
What kind of vector is in the template? 1:N

### ISSUE THREAD

**Issue by LionLion888** [usnistgov/frvt#102]
Hi there,

When **createTemplate(TemplateRole=Enrollment_1N)**, the implementation will return a template to the calling application. 

I am wondering to know what kind of vector is in the template? Is it a **feature** from the face detection or it can be a **similarity score** produce by the face recognition as well. 

<img src=https://imgur.com/PZXbC3i.png width=60% />

Besides, if the vector in the template can be a similarity score, does that mean the **Template Generation** will deal with face detection and face recognition, also the total of the face detection and face recognition execution time need to within 1.5 sec.

<img src=https://imgur.com/XIoYV78.png width=60% />

**Comment by paddygr** [comment]
createTemplate produces feature data from one image.   The function takes one image, so there is nothing to match against, so there is no recognition, no similarity score.

From: LionLion888 ***@***.***>
Date: Tuesday, August 8, 2023 at 6:18 AM
To: usnistgov/frvt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [usnistgov/frvt] What kind of vector is in the template? 1:N (Issue #102)

Hi there,

When createTemplate(TemplateRole=Enrollment_1N), the implementation will return a template to the calling application.

I am wondering to know what kind of vector is in the template? Is it a feature from the face detection or it can be a similarity score produce by the face recognition as well.

[Image removed by sender.]<https://camo.githubusercontent.com/3ca920d1ec7bce0560c019b1465b782d8c384f2cdecb238e67c77556b444f8bd/68747470733a2f2f696d6775722e636f6d2f505a58624333692e706e67>

Besides, if the vector in the template can be a similarity score, does that mean the Template Generation will deal with face detection and face recognition, also the total of the face detection and face recognition execution time need to within 1.5 sec.

[Image removed by sender.]<https://camo.githubusercontent.com/dcf20b311188703d4941006761e76f94684dae44375932d1d61d1542e027b360/68747470733a2f2f696d6775722e636f6d2f58496f595637382e706e67>
