### ISSUE TITLE
Is there any memory limit in 1:N  Identification?

### ISSUE THREAD

**Issue by PeggyWang888** [usnistgov/frvt#103]
I am working on FRVT 1:N, and my query is : is there any memory limit in 1:N  Identification?

**Comment by mlngan** [comment]
Per Section 4 of the [General Evaluation Specifications](https://pages.nist.gov/frvt/api/FRVT_common.pdf), each evaluation machine has at least 128 GB of memory. We anticipate that 16 processes can be run without time slicing, though NIST will handle all multiprocessing work via fork().  Hope this information helps.
