### ISSUE TITLE
Undefined enums

### ISSUE THREAD

**Issue by hiroosaito** [usnistgov/frvt#104]
The enums Action::EstimateAge and Action::VerifyAge in "common/src/util.cpp" are not defined in "common/src/include/util.h", and which causes a compile error.

Could you take care of the issue?

**Comment by kayee-nist** [comment]
Updated the file, please try again.  Thank you.

**Comment by golunovas** [comment]
It still doesn't work. There are two "<" symbols in lines 122-123 that need to be removed.

**Comment by kayee-nist** [comment]
file is fixed, try again thank you.
