### ISSUE TITLE
`<` wrong syntax in utils.h

### ISSUE THREAD

**Issue by JackLin-Authme** [usnistgov/frvt#105]
https://github.com/usnistgov/frvt/blob/b73285b59ab6b6b6b00a359ccd87bf06f7cba049/common/src/include/util.h#L122
https://github.com/usnistgov/frvt/blob/b73285b59ab6b6b6b00a359ccd87bf06f7cba049/common/src/include/util.h#L123
There are unexpected characters `<` in util.h leading fail.

<img width="1020" alt="截圖 2023-08-23 16 38 28" src="https://github.com/usnistgov/frvt/assets/66769915/690ed0f7-0630-4b73-bfd3-db14716e5e83">

**Comment by kayee-nist** [comment]
fixed the issue and file is updated, thank you.
