### ISSUE TITLE
Does 1:1 Face test on images rotated to 90 or 180 degree?

### ISSUE THREAD

**Issue by JackLin-Authme** [usnistgov/frvt#107]
I saw 2 cases in common/faces folder, rotated_90.ppm and rotated_180.ppm.

Is it mean that there are some rotated image will be test in 1:1 protocol?

**Comment by mlngan** [comment]
We do not intend on testing with rotated images in our actual test.  HOWEVER, these edge cases were put into the validation package to test that your algorithm does not crash in the event such unexpected cases are encountered.

**Comment by mnktn** [comment]
> Yes. 1:1 and 1:N share a number of images in the validation set.

Thanks. And what about the _evaluation_ 1:N dataset? Should we expect rotated images there?
