### ISSUE TITLE
run_validate_ae.sh throws warnings from the sanityCheck

### ISSUE THREAD

**Issue by golunovas** [usnistgov/frvt#108]
During the validation process I'm getting the following warnings:
```
Sanity checking validation output 
validation/estimateAge_1.log - 
[WARNING] The following entries in .log generated non-successful return codes:
sed: can't read validation/.log: No such file or directory
[DONE]
validation/estimateAge_2.log - [DONE]
validation/verifyAge.log - 
[WARNING] The following entries in .log generated non-successful return codes:
sed: can't read validation/.log: No such file or directory
[DONE]
```

It looks like `$action` variable is not defined here: https://github.com/usnistgov/frvt/blob/master/age-estimation/run_validate_ae.sh#L50 and the same issue is present here: https://github.com/usnistgov/frvt/blob/master/age-estimation/run_validate_ae.sh#L42

**Comment by kayee-nist** [comment]
It has been corrected, please update the file and thank you.
