### ISSUE TITLE
Time Limits clarification for creation of M Templates from a single image

### ISSUE THREAD

**Issue by ElisonSherton** [usnistgov/frvt#111]
Hi everyone!

In **Table 6** from [this document](https://pages.nist.gov/frvt/api/FRVT_ongoing_11_api.pdf), we can see that there is a single image and if there are M faces which our algorithm detects, then we will return M templates in the output of `createFaceTemplate` API call.

However as per **Table 1** from the same document, we can see that feature extraction should only take 1500 ms per image. And only if there are `K` images of a single person, the time limit would be scaled up by that factor. 

Am I correct in understanding following scenarios?

- We detect 5 faces in an image. Do we get 1500 ms to perform feature extraction of all the five faces **OR** do we get 1500 $\times$ 5 = 7500 ms
- We are given 5 images and we detect 1 face in each image. Will we get 1500 $\times$ 5 = 7500 ms to do the feature extraction?

Thanks,
Vinayak.

**Comment by xsacha** [comment]
All the images you are talking about have just a single face even if you detect thousands.
You get 1500ms per image (which is one face).

**Comment by ElisonSherton** [comment]
In `4.4.4` of the API document, we noticed the following

![image](https://github.com/usnistgov/frvt/assets/45599762/f9e6e16f-3680-4e2d-8fdb-33d418a7f4ec)

So, we do have images which have more than one face in them right?

Thanks,
Vinayak.

**Comment by xsacha** [comment]
Yeah there is just one foreground face

**Comment by ElisonSherton** [comment]
Hi @xsacha 

Agreed that there is one foreground face, but since we're not aware of which face is foreground or background, we can return M templates and then as mentioned in points 3 and 4 of section 4.4.4, matching could be done across all sets of enrollment and verification templates right?

For that we need to send multiple face templates per image and for that I was asking will we get more time or do we still have to abide to 1500 ms for getting the templates for all the faces from a single image?

Thanks,
Vinayak.

**Comment by mlngan** [comment]
We are only conducting formal timing runs on single-person (single template) images.  While we are not enforcing timing limits for multi-person (multiple templates) images, please implement something sensible (e.g., 1500 ms * the number of faces detected would be OK).

**Comment by ElisonSherton** [comment]
Thanks for the clarification @mlngan 

This really helps!
