### ISSUE TITLE
What is include in the 1:N finalization time limited?

### ISSUE THREAD

**Issue by LionLion888** [usnistgov/frvt#112]
Hi there,

In the FRVT 1:N time limits ([5.1. Time limits](https://pages.nist.gov/frvt/api/FRVT_IREX_ongoing_1N_api.pdf)), I'm wondering to know what is included in the **1:N finalization time limited** (mark with red box)?

<img src="https://github.com/usnistgov/frvt/assets/133086055/9875eba9-52a5-449e-97a1-2a8d797343dc" width="70%" >

In detail, which following is 1:N finalization time limited (mark with red box) represented?

A. Feature extraction execution time (mark with blue box) + Enrolled database execution time (mark with green box)

B. Only include enrolled database execution time (mark with green box)

<img src="https://github.com/usnistgov/frvt/assets/133086055/6932e77a-9136-4429-9bad-5faacad643c9" width="70%" >

**Comment by paddygr** [comment]
Answer is B.  Finalization takes N templates and produces a searchable data structure.

From: LionLion888 ***@***.***>
Date: Wednesday, October 18, 2023 at 2:13 AM
To: usnistgov/frvt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [usnistgov/frvt] What is include in the 1:N finalization time limited? (Issue #112)

Hi there,

In the FRVT 1:N time limits (5.1. Time limits<https://pages.nist.gov/frvt/api/FRVT_IREX_ongoing_1N_api.pdf>), I'm wondering to know what is included in the 1:N finalization time limited (mark with red box)?
[https://user-images.githubusercontent.com/133086055/276111081-9875eba9-52a5-449e-97a1-2a8d797343dc.png]<https://user-images.githubusercontent.com/133086055/276111081-9875eba9-52a5-449e-97a1-2a8d797343dc.png>

In detail, which following is 1:N finalization time limited (mark with red box) represented?

A. Feature extraction execution time (mark with blue box) + Enrolled database execution time (mark with green box)

B. Only include enrolled database execution time (mark with green box)
[https://user-images.githubusercontent.com/133086055/276111122-6932e77a-9136-4429-9bad-5faacad643c9.png]<https://user-images.githubusercontent.com/133086055/276111122-6932e77a-9136-4429-9bad-5faacad643c9.png>

**Comment by LionLion888** [comment]
Hi paddygr,

I got it! Thanks for your response.
