### ISSUE TITLE
[FRVT 1:1] Can I edit the header file? 

### ISSUE THREAD

**Issue by yhbembedding** [usnistgov/frvt#113]
nullimplfrvt11.h
 I fix it from uint8_t to float.
![Screenshot from 2023-10-23 11-17-58](https://github.com/usnistgov/frvt/assets/55545444/463cad6c-95ac-4e06-a5f6-96f09b1065db)

**Comment by mlngan** [comment]
You cannot modify any of the source code that we have published.  Please consider the example provided in https://github.com/usnistgov/frvt/blob/master/11/src/nullImpl/nullimplfrvt11.cpp on how to convert between uint8_t and float.

**Comment by yhbembedding** [comment]
Thanks for your answer, in file cpp, matching is random. Can I modify it.
![Screenshot from 2023-10-24 08-15-49](https://github.com/usnistgov/frvt/assets/55545444/cc8014f3-000b-4354-b6f3-d7199a5f53ae)
What are editable files?, util.h, util.cpp,validate11.cpp ?

**Comment by paddygr** [comment]
You implement whatever match you want, in your compiled library.  You must not change the API.  You cannot edit those files.

From: Hoàng Bá Ý ***@***.***>
Date: Monday, October 23, 2023 at 9:20 PM
To: usnistgov/frvt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [usnistgov/frvt] [FRVT 1:1] Can I edit the header file? (Issue #113)

Thanks for your answer, in file cpp, matching is random. Can I modify it.
[Image removed by sender. Screenshot from 2023-10-24 08-15-49]<https://user-images.githubusercontent.com/55545444/277520535-cc8014f3-000b-4354-b6f3-d7199a5f53ae.png>
What are editable files?, util.h, util.cpp,validate11.cpp ?

**Comment by shritor** [comment]
![Screenshot from 2023-11-30 09-19-34](https://github.com/usnistgov/frvt/assets/149577702/45ea4c75-e23d-4a82-b1d4-a8ac9a0c50e7)
some member ?  can I add some attribute
