### ISSUE TITLE
Conversion of uint8_t to float for template

### ISSUE THREAD

**Issue by rishidd1** [usnistgov/frvt#123]
Hi! I have a doubt regarding the conversion of unint8_t to float for the template vector. In the validate1N.cpp file templ(template) variable datatype is declared as vector<uint8_t>. The datatype of embeddings from the recognizer model is of data type float. How can I obtain a conversion of uint8 to float. Also, if I use reinterpret cast for conversion, the values I get are incorrect. Why havent NIST utilized data type of templ as float or double instead of uint8_t?

**Comment by mlngan** [comment]
Many developers use floating point internally, but we use a generic byte stream to allow any type, including a constructed type.  One solution is to use casting, for example.
 
// Cast float to uint8_t during template creation
const uint8_t* bytes = reinterpret_cast<const uint8_t*>(fv.data());
      
// Cast uint8_t back to float during match
float *featureVector = (float *)enrollTemplate.data();
 
Can you elaborate on what you mean by the values are incorrect when you use reinterpret_cast?
