### ISSUE TITLE
Submission of Dynamically linked library(.so file) to NIST.

### ISSUE THREAD

**Issue by rishidd1** [usnistgov/frvt#124]
Hi I have used onnxruntime and opencv libraries in my face recognition implementation. NIST asks vendors to submit a single .so file (libfrvt_<track>_<provider>_<sequence>.so) (core implementation) as a part of tar package. The only library that will be explicitly linked to test driver is the core library. Currently I am working in docker environment that has opencv and onnxruntime dependencies and generating the .so file. However, I am unable to run the testdriver script outside the docker environment as no dependencies are there. 
Can I provide supplemental .so libraries (containing the dependencies) along with the core .so file? If yes then how?

**Comment by mlngan** [comment]
Yes, you may include supplemental .so libraries in the same ./lib folder where your core library is located.
