### ISSUE TITLE
Doubt regarding NIST Public Key

### ISSUE THREAD

**Issue by ElisonSherton** [usnistgov/frvt#134]
Hi!

I am trying to encrypt my final submission file using the outlines [mentioned here](https://www.nist.gov/system/files/documents/2021/10/25/nist_encryption.pdf).

As mentioned in section 2.3, I try to import the NIST public key for FRTE [provided here](https://www.nist.gov/system/files/documents/2021/10/25/nist_encryption.pdf) in the second row.

However the key that I get is slightly different. The fingerprint obtained after importing the key is the same as the one mentioned in submission document but the key is different as can be seen below.

![key_mismatch](https://github.com/usnistgov/frvt/assets/45599762/48e32547-5bc7-4be4-8e41-0e0f980431d4)

Is this acceptable for the submission or am I missing something when importing the key?

Thanks,
Vinayak.

**Comment by paddygr** [comment]
If you are saying the string 856B9B28 does not match the string 5A18F9... then that is expected

If you are saying that something else doesn't match. then email us again.
________________________________
From: Vinayak Nayak ***@***.***>
Sent: Friday, May 24, 2024 3:23 AM
To: usnistgov/frvt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [usnistgov/frvt] Doubt regarding NIST Public Key (Issue #134)


Hi!

I am trying to encrypt my final submission file using the outlines mentioned here<https://www.nist.gov/system/files/documents/2021/10/25/nist_encryption.pdf>.

As mentioned in section 2.3, I try to import the NIST public key for FRTE provided here<https://www.nist.gov/system/files/documents/2021/10/25/nist_encryption.pdf> in the second row.

However the key that I get is slightly different. The fingerprint obtained after importing the key is the same as the one mentioned in submission document but the key is different as can be seen below.

key_mismatch.png (view on web)<https://github.com/usnistgov/frvt/assets/45599762/48e32547-5bc7-4be4-8e41-0e0f980431d4>

Is this acceptable for the submission or am I missing something when importing the key?

Thanks,
Vinayak.

**Comment by ElisonSherton** [comment]
Yeah that's what I meant. Thanks for the confirmation!
