### ISSUE TITLE
Disparity of median enrollment time when running on single core.

### ISSUE THREAD

**Issue by rishidd11** [usnistgov/frvt#137]
The NIST document specifies that the median enrollment time must be under 1.5 seconds on a single core, tested on an Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz. In the run_testdriver.sh script, the num_forks argument is used to run validate11.cpp.

When I run the script on a single core using the command taskset --cpu-list 1 run_validate11.sh, the enrollment time for multiple processes (i.e., num_forks = 4) increases fourfold compared to a single process. However, there is no increase in time for multiple processes when I run the script without the taskset command.

How does NIST internally check the median enrollment time? Do they use the taskset command to limit the number of CPUs to one?

**Comment by mlngan** [comment]
During our timing test, we only run with a single process (and limit the number of CPUs to one).  We run and time the template generation call over many iterations, then take the median of those timing values.
