### ISSUE TITLE
Unexpected path of `video1` for `run_validate_ae.sh`

### ISSUE THREAD

**Issue by paplhjak** [usnistgov/frvt#138]
When running `./run_validate_ae.sh`, the execution fails with:
![image](https://github.com/usnistgov/frvt/assets/52961799/ba30b30c-6a18-4efd-ad18-88b48591c287)

This can be fixed by moving the `video1` folder down by one directory, however, this should not be expected of the user.

**Comment by kayee-nist** [comment]
We've updated the file with the correct path.  Thank you.
