### ISSUE TITLE
Some questions related to edb and manifest

### ISSUE THREAD

**Issue by YYY7C** [usnistgov/frvt#144]
I would like to ask some questions related to edb and manifest. Regarding the names of edb and manifest during the finalizeEnrollment process, should these names be changed based on the dataset?

`const std::string edb{"mei.edb"};
const std::string manifest{"mei.manifest"};`

**Comment by mlngan** [comment]
Those EDB and manifest names are just an example used in the null implementation.  You can name your files whatever you'd like.
