### ISSUE TITLE
The validation package contains these edge-case images to make sure your algorithm doesn't crash.  The validation script will only output a warning message for the images that didn't not successfully generate a template, but it will proceed to generate a submission package.  The warnings outputted are for your information in case you detect unexpected behavior.

### ISSUE THREAD

**Issue by pravar1799** [usnistgov/frvt#149]
The validation package contains these edge-case images to make sure your algorithm doesn't crash.  The validation script will only output a warning message for the images that didn't not successfully generate a template, but it will proceed to generate a submission package.  The warnings outputted are for your information in case you detect unexpected behavior.

_Originally posted by @mlngan in https://github.com/usnistgov/frvt/issues/27#issuecomment-602556176_

**Comment by pravar1799** [comment]
@mlngan , Are edge case images, such as black.ppm or rotated images, included in the NIST test during the search/enroll process, or are they solely part of the validation package available on GitHub?

**Comment by mlngan** [comment]
We don't intend on testing with such edge case images, but the check in the validation package is to ensure that in the unlikely event your algorithm encounters a strange image, that it handles it gracefully rather than crash.

**Comment by pravar1799** [comment]
@mlngan thank you for the response!
