### ISSUE TITLE
Compiler version

### ISSUE THREAD

**Issue by igriffer** [usnistgov/frvt#17]
Can I use g++ version greater than 4.8.5? Some libraries do not work with this version of compiler. libtorch works well with g++ 4.9.2 from devtoolset-3-gcc-c++ but breaks when using 4.8.5. https://github.com/pytorch/pytorch/issues/14981

**Comment by mlngan** [comment]
Have you tried building your libraries using devtoolset (gcc 4.9.2), and running it on our standard CentOS 7.6 image (gcc 4.8.5)?

**Comment by igriffer** [comment]
Thanks for the advice. I was able to successfully build the library on g++ 4.9.2 and use it with g++ 4.8.5. I think the issue can be closed.
