### ISSUE TITLE
Do I need to prove my status while submitting?

### ISSUE THREAD

**Issue by deidonum** [usnistgov/frvt#19]
We are going to participate in FRVT. Application form says that developers are eligible to participate. Should we somehow prove that we are developers and algorithm is ours?
Thank you.

**Comment by anguoyang** [comment]
@deidonum I have the same question, have you get feedback?

**Comment by paddygr** [comment]
You need to complete the Application Form and send it to us. Please email us when you do. You can send your algorithm at any time. We will not evaluate it unless we receive the completed Application Form.
