### ISSUE TITLE
Gcc version 

### ISSUE THREAD

**Issue by kotbegemot** [usnistgov/frvt#21]
Can I update the compiler version to gcc 5 ?
can I switch validate11 builds to C++ 14 ?

**Comment by mlngan** [comment]
If you need to build your libraries with gcc 5, have you tried building your libraries using devtoolset and running it on our standard CentOS 7.6 image?

**Comment by kotbegemot** [comment]
I checked on CentOS 7 there is DevTools-7. https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/
I found a workaround we learned how to build gcc 4.9.2 .
can the project be compiled by gcc 4.9.2 and submitted to the competition ?

**Comment by mlngan** [comment]
If your submission is built with devtoolset and runs on the CentOS 7.6 image on our validation package, it should be fine.

**Comment by kotbegemot** [comment]
Thanks for the help.
