### ISSUE TITLE
A limitation of the library on a thread of execution

### ISSUE THREAD

**Issue by kotbegemot** [usnistgov/frvt#22]
We use mxnet to implement machine learning. 
We have made sure that mxnet does not generate a large number of threads for calculations.

However, we are showing a warning from the verification script :

```bash
[WARNING] We've detected that your software may be threading or using other multiprocessing techniques during template creation.  The number of threads detected was 3 and it should be 2.  Per the API document, implementations must run single-threaded.  In the test environment, there is no advantage to threading, because NIST will distribute workload across multiple blades and multiple processes.  We highly recommend that you fix this issue prior to submission.

```
How critical is this warning ?

**Comment by mlngan** [comment]
If the additional thread from mxnet isn't doing any work, it should be fine.  We will assess the threading situation on a case-by-case basis.

**Comment by kotbegemot** [comment]
Thanks for the help.
