### ISSUE TITLE
Example file version.txt in folder doc 

### ISSUE THREAD

**Issue by kotbegemot** [usnistgov/frvt#23]
Is there an example of filling in a version.txt file in the doc folder ?

**Comment by mlngan** [comment]
I don't have an example.  Version.txt should contain vendor-specific information on the specific algorithm that is being sent for testing.

**Comment by kotbegemot** [comment]
Thanks for the help.

**Comment by anguoyang** [comment]
@kotbegemot have you solved it? it is Okay that just put, for example 1.0.0 in the first line of Version.txt? @mlngan

**Comment by mlngan** [comment]
yes - the information is supposed to keep track of the version of your algorithm submitted.
