### ISSUE TITLE
library path

### ISSUE THREAD

**Issue by buganini** [usnistgov/frvt#24]
Please explicitly set LD_LIBRARY_PATH in run_testdriver.sh so that it can be used with 3rd libraries without modification or question.

Or is it safe to use -rpath=$ORIGIN ?

**Comment by suryaprakaz** [comment]
Hey, I have a similar problem where I'm not able to link against 3rdparty libraries. How did you solve it? Can you help?

**Comment by buganini** [comment]
I set environment variable outside like: env LD_LIBRARY_PATH=lib ./scripts/run_testdriver.sh

**Comment by wfcb-85** [comment]
What I did to get rid of that problem is to link against 3rdpart libraries statically.
