### ISSUE TITLE
What does std::vector<float> fv mean?

### ISSUE THREAD

**Issue by anguoyang** [usnistgov/frvt#26]
In your example code in nullImplFRVT11::createTemplate:
    
std::vector<float> fv = {1.0, 2.0, 8.88, 765.88989};
const uint8_t* bytes = reinterpret_cast<const uint8_t*>(fv.data());
int dataSize = sizeof(float) * fv.size();
templ.resize(dataSize);
memcpy(templ.data(), bytes, dataSize);

It seems that fv represent the face feature array right? however there are multi faces(const Multiface &faces), I just wonder why only one feature array here, however for the eye coordinates, it does:
    for (unsigned int i=0; i<faces.size(); i++) {
        eyeCoordinates.push_back(EyePair(true, true, i, i, i+1, i+1));
    }

from the parameter, it seems multi-face with only single feature array(std::vector<uint8_t> &templ), which I am really confusing, could you kindly help me? thank you

**Comment by mlngan** [comment]
The code snippet with the feature vector is just an example showing one way of storing a vector of floats into a vector of uint8_t.  Regardless of the number of faces contained within the Multiface (vectors of faces), your algorithm should return a single template.  The template could be N number of feature vectors extracted out of N number of face images concatenated together, it could be a fusion of all your feature vectors into a single feature vector, we don't know or care about those details.  

Please note that for most face images, we expect only a single face to be in the photo.  In the rare event that more than one face is detected in an image, features should be extracted from the foreground face, that is, the largest face in the image.

**Comment by cannguyen275** [comment]
>> The template could be N number of feature vectors extracted out of N number of face images concatenated together, it could be a fusion of all your feature vectors into a single feature vector, we don't know or care about those details.

Do faces contained within the Multiface belong to the same person @mlngan?
This information is very important to be clear because I can fuse all feature vectors into a single feature vector of the same person only.

**Comment by mlngan** [comment]
Yes, all faces contained within the Multiface will belong to the same person.
