### ISSUE TITLE
All faces need to be detected before submission?

### ISSUE THREAD

**Issue by anguoyang** [usnistgov/frvt#27]
hi @mlngan  sorry for interrupt you again.
When I run the run_validate_11.sh, it seems that all the faces need to be detected before generate the submission package, the problem is: some of the face images are actually white/black blank or too small for detection or 90 angles which is also difficult for detection, I return the "FacedetectionError" but it seems unless we detect all the face images otherwise will not generate the submission package, please correct me if I am wrong. thank you

**Comment by mlngan** [comment]
The validation package contains these edge-case images to make sure your algorithm doesn't crash.  The validation script will only output a warning message for the images that didn't not successfully generate a template, but it will proceed to generate a submission package.  The warnings outputted are for your information in case you detect unexpected behavior.

**Comment by anguoyang** [comment]
Hi @mlngan  I have return success or failure in all possible paths, but still with that problem, do you mean that I need to handle these failures? can you give an example? thank you

**Comment by anguoyang** [comment]
Faces are not detected.scripts/run_testdriver.sh: line 92: kill: (23144) - No such process
[ERROR] Enrollment template creation validation (single process) failed
run_testdriver.sh failed

**Comment by mlngan** [comment]
Per the API: [https://pages.nist.gov/frvt/api/FRVT_ongoing_11_api_4.0.pdf], section 4.4.3, even when unable to extract features (and you return a non-successful return code), the output shall be a template that may be passed to the matchTemplates() function without error. That is, this routine must internally encode "template creation failed" and the matcher must transparently handle this.

**Comment by anguoyang** [comment]
@mlngan thank you, now it works.
Another minor question, can we put the .so file into config directory? most .so files are in ./lib , but there is also a .so file loaded with model files during initialization, could we put that .so into config directory?

**Comment by mlngan** [comment]
@anguoyang Your primary libfrvt_11_xxx_xxx.so file needs to go into the ./lib folder.  If you have libraries that are needed by your models stored in the ./config folder, those can reside in the ./config folder.

**Comment by sam7177** [comment]
@mlngan 
I have one additional .so file of only 4MB in the lib/ directory in addition to libfrvt_11_xxx_xxx.so. Will that be acceptable as a valid submission? Or is there a hard requirement of only one file in lib directory?

**Comment by paddygr** [comment]
You can have an unlimited number of files lib/


From: sam7177 ***@***.***>
Date: Wednesday, May 26, 2021 at 19:23
To: usnistgov/frvt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [usnistgov/frvt] All faces need to be detected before submission? (#27)

@mlngan<https://github.com/mlngan>
I have one additional .so file of only 4MB in the lib/ directory in addition to libfrvt_11_xxx_xxx.so. Will that be acceptable as a valid submission? Or is there a hard requirement of only one file in lib directory?
