### ISSUE TITLE
Template type

### ISSUE THREAD

**Issue by nqkhai1706** [usnistgov/frvt#29]
Hello @mlngan ,
I am going to participate to the challenge, but I am confusing for a problem:
About the template type, could I change the uint8_t in const std::vector<uint8_t> &verifTemplate and all related variables? The reason is my algorithm's output is in real numbers, this type cannot store the real numbers. Or I must modify my algorithm?
Thank you!!

**Comment by mlngan** [comment]
The template type cannot be changed.  Please take a look at the provided null implementation for an example of how one might store/retrieve a vector of floats from a vector of uint8_t.

https://github.com/usnistgov/frvt/blob/master/11/src/nullImpl/nullimplfrvt11.cpp

**Comment by nqkhai1706** [comment]
@mlngan thank you a lot!
Sorry for bother you again. I saw and tried, but I cannot get exactly my float.
I saw that I can get maximum only 6 characters. Eg. I store 765.88989, but retrieve only 765.89.
Maybe I did a mistake?
Thank you!

**Comment by cannguyen275** [comment]
> I saw that I can get maximum only 6 characters. Eg. I store 765.88989, but retrieve only 765.89.

I've got the same problem. It strongly affects algorithm accuracy. A vector of uint8_t cannot present a float-type feature
@nqkhai1706 Did you find any solutions?
@mlngan Do you have any ideas for this?

**Comment by mlngan** [comment]
@cannguyen275 The float is being stored and retrieved correctly on my end.  Try setting the precision of the output stream when printing.  For example, try adding:
 
cout.precision(5); 
for (unsigned int i=0; i<this->featureVectorSize; i++) {
    std::cout << fixed << featureVector[i] << std::endl;
}

**Comment by paddygr** [comment]
/* Note: example code, potentially not portable across machines. */
    std::vector<float> fv = {1.0, 2.0, 8.88, 765.88989};
    const uint8_t* bytes = reinterpret_cast<const uint8_t*>(fv.data());
    int dataSize = sizeof(float) * fv.size();
    templ.resize(dataSize);
    memcpy(templ.data(), bytes, dataSize);


From: Kei ***@***.***>
Date: Monday, May 17, 2021 at 05:50
To: usnistgov/frvt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [usnistgov/frvt] Template type (#29)

I saw that I can get maximum only 6 characters. Eg. I store 765.88989, but retrieve only 765.89.

I've got the same problem. It strongly affects algorithm accuracy. A vector of uint8_t cannot present a float-type feature
@nqkhai1706<https://github.com/nqkhai1706> Did you find any solutions?
@mlngan<https://github.com/mlngan> Do you have any ideas for this?
