### ISSUE TITLE
threshold to classify as the same person

### ISSUE THREAD

**Issue by vfacer** [usnistgov/frvt#34]
We are preparing a validation package for FRVT11. Log files with similarity score (range from 0.00 to 1.00) are successfully generated. May we know which threshold FRVT will use to determine a pair of template is from the same person or different. 
Or we just need document it clearly in submission email?

Much appreciated any help,

-Bill

**Comment by mlngan** [comment]
We will run both mated (same person) and non-mated (different person) comparisons.  We expect mated scores to be high and non-mated scores to be low.  Then we will conduct ROC/DET analysis such that we sweep through a large number of score thresholds to determine what the false negative and false positive rates are at those thresholds.  So to answer your question - we won't be using any single threshold - we will analyze many thresholds.  Hope this helps.
