### ISSUE TITLE
how to link variable declared in initialize to use in createTemplate

### ISSUE THREAD

**Issue by quocnhat** [usnistgov/frvt#35]
hello, I am interested in Nist and will submit for validation soon. Now I got in a trouble, please help.
I defined and loaded a model-param from Initialize, but I am confusing at how to call the model in createTemplate. 
Please give some advice or Am I misunderstanding somewhere? Much appreciated any help.
-- Nhat

**Comment by mlngan** [comment]
One way to do it is to declare your model param/variable as a member variable in your implementation class - see https://github.com/usnistgov/frvt/blob/master/11/src/nullImpl/nullimplfrvt11.h for example.

**Comment by quocnhat** [comment]
Thank you, I got it
