### ISSUE TITLE
Can I build a static shared library in linux debian and run it in CentOS ?

### ISSUE THREAD

**Issue by quocnhat** [usnistgov/frvt#36]
Hello, I am trying to build -static shared library in ubuntu 18.04 so that it is able to run in CentOs but I got some "undefined reference to" errors when compiling "compile_and_run.sh". Does anyone try this solution? any comment is appreciated, thank you.
Scanning dependencies of target validate11
[ 33%] Building CXX object src/testdriver/CMakeFiles/validate11.dir/home/cybercore/workspace/frvt/common/src/util/util.cpp.o
[ 66%] Building CXX object src/testdriver/CMakeFiles/validate11.dir/validate11.cpp.o
[100%] Linking CXX executable ../../../bin/validate11
../../../lib/libfrvt_11_cybercore_001.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const'
../../../lib/libfrvt_11_cybercore_001.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
../../../lib/libfrvt_11_cybercore_001.so: undefined reference to `__cxa_throw_bad_array_new_length'
../../../lib/libfrvt_11_cybercore_001.so: undefined reference to `operator delete(void*, unsigned long)'

**Comment by quocnhat** [comment]
@mlngan pls help. I know that the " undefined reference to std::__cxx is from the difference of gcc version from third-party library ( gcc 7.5.0 ubuntu 18.04) and the compiler (gcc 4.8.5 Red Hat).  I wonder if I can build third-party libraries ( static shared) on alternative gcc 4.8.5 ubuntu or not?

**Comment by mlngan** [comment]
Your software will have to run on our CentOS 7.6 image.  As for the difference between compiler versions, have you tried building your libraries using devtoolset (gcc 7.5.0), and running it on our standard CentOS 7.6 image (gcc 4.8.5)?

**Comment by quocnhat** [comment]
thank you for quick response. 
Currently, I am using ubuntu. I built my libraries based on Cmake gcc 7.5.0. But it failed to link to centOS 7.6 image (gcc 4.8.5) ( as shown at the beginning of this post, most errors come from the difference of gcc versions). my question is: Is there any way to build libraries based on ubuntu that can link to Nist's environment?

**Comment by mlngan** [comment]
It's not going to work given your library is being built with a later version of gcc.  Can you build your libraries with devtoolset (e.g., https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/) on CentOS instead?

**Comment by quocnhat** [comment]
for some reason, I have to build on ubuntu, sorry about that. However, what if my lib is being built on ubuntu with older gcc version., say 4.8.5 ( or 4.9.2)? guess it is ok for the linking to CentOS image 7.6 ( 4.8.5) ?
