### ISSUE TITLE
Matching Templates (Multiple Processes) PID 23985 exited due to signal 11...

### ISSUE THREAD

**Issue by sangjinhong** [usnistgov/frvt#38]
I'm now testing frvt 1:1 for our solution.

I met the following messages:

Matching Templates (Multiple Processes) PID 23985 exited due to signal 11
PID 23986 exited due to signal 11
PID 23988 exited due to signal 11
[ERROR] Match validation failed

Can you guide how to fix the problem?

Thanks.

Hong.

**Comment by mlngan** [comment]
Your messages is an indication that a segmentation fault occurred - you could try running valgrind or gdb to see what's causing the issue.  Perhaps also check that you're not releasing memory twice somewhere (e.g., in your destructor).
