### ISSUE TITLE
Error authenticate the Nist key

### ISSUE THREAD

**Issue by quocnhat** [usnistgov/frvt#39]
I am confusing at email my public key to Nist, Don't really understand here. What is it and how do I know my public key is sent to Nist successfully?

![image](https://user-images.githubusercontent.com/19263564/88777491-79bbf880-d1b1-11ea-8c39-927a88291729.png)

**Comment by mlngan** [comment]
Your public encryption key is the result of step 2 of the process, which should be named forfrvt11.gpg.  You need to email that file to frvt@nist.gov.

**Comment by quocnhat** [comment]
I need to re-submit my solution to Nist. But unfortunately, my default key disappears. Can I generate another key and resubmit, including forfrvt11.gpg? It is definitely different from the one printed in the agreement ( already sent by post).
Thank you

**Comment by mlngan** [comment]
If you generate a new key, you will have to send us an updated participation agreement with the new key fingerprint and email us the new gpg file.
