### ISSUE TITLE
Two submissions before the four months

### ISSUE THREAD

**Issue by mlourencoeb** [usnistgov/frvt#40]
Hello, 

This is not really an issue, it is more a doubt. I believe last year it was possible to submit two versions of algorithms, and then every submission would need to wait for four months until a new one is done. I did it in the past company, so I'm sure about this.

Is this rule currently valid?

Thanks for the clarification.

Best,
Miguel

**Comment by mlngan** [comment]
For the FRVT 1:1, 1:N, and Quality tracks, participants may send **one** submission as often as every four calendar months from the last submission for evaluation.  We are no longer allowing two submissions for first-time participants.

**Comment by mlourencoeb** [comment]
Thanks for updade. Appreciate it!

**Comment by fisakhan** [comment]
@mlngan What if my submission has an error/problem in code, for example, generating too many threads. Do you still start counting 4 month for my submission? Or you start counting 4 month when my submission is running successfully on NIST's end?

**Comment by mlngan** [comment]
You will be allowed to submit your next submission 4 months from the date you send us a successfully running algorithm.
