### ISSUE TITLE
Twice call to distructor ~NullImplFRVT11()

### ISSUE THREAD

**Issue by fisakhan** [usnistgov/frvt#41]
The NIST API calls ~NullImplFRVT11() two times after each call to "bin/validate11 createTemplate -x enroll -c $configDir -o $outputDir -h $outputStem -i $inputFile -t $numForks -j $templatesDir retEnroll=$?" Both the destructors use different process ids. This does not allow my program to release memory. I expect only one call to ~NullImplFRVT11(). Whats the problem and how to restrict processes to only one?

**Comment by mlngan** [comment]
The testdriver forks child processes to do work, and the destructor gets called once for each child process + once for the parent process.  We use this approach in our actual test, so you will need to address this.
