### ISSUE TITLE
Incorrect path

### ISSUE THREAD

**Issue by kotbegemot** [usnistgov/frvt#44]
When the [script]( https://github.com/usnistgov/frvt/blob/master/11/scripts/run_testdriver.sh
) is running, an empty path is passed.
The system centos 7.6 did not repeat itself.

```bash
echo -n "Checking for hard-coded config directory "
tempConfigDir=$(pwd)/otherConfig
chmod 775 $configDir; mv $configDir $tempConfigDir; chmod 550 $tempConfigDir
bin/validate11 createTemplate -x enroll -c $tempConfigDir -o $outputDir -h $outputStem -i $inputFile -t $numForks -j $templatesDir
retEnroll=$?
```

@mlngan

**Comment by mlngan** [comment]
Unsure why tempConfigDir would be an empty path as it works on my end.  But I've reverted back to not appending $(pwd) in front of the config dirs, so it should work now.  New OS requirement is not CentOS 8.2.  b18c70f
