### ISSUE TITLE
How to confirm which pictures are the same person

### ISSUE THREAD

**Issue by aliqing0122** [usnistgov/frvt#46]
Hi @mlngan how do i categorize the pictures provided on github(https://github.com/usnistgov/frvt/tree/master/common/images)?
How do i know which pictures are the same person?

**Comment by mlngan** [comment]
The purpose of the validation package is to ensure your submission adheres to the API and tests a bunch of edge cases to make sure your software doesn't crash.  The images published aren't necessarily used to test the accuracy of your software, so we do not publish any sort of ground truth for the identities.
