### ISSUE TITLE
free(): invalid pointer after trying to load torch model

### ISSUE THREAD

**Issue by wfcb-85** [usnistgov/frvt#49]
Hello, 
After I was trying to load a torch model, and it failed, I get every time I execute run-validate_11.sh an invalid pointer error. The error persists even when I set the code as it originally was and build it again. For info, I'm building the null implementation. 

You can find below the message of the error:
 -------------------------
Running 1:1 validation
-------------------------

Checking for hard-coded config directory free(): invalid pointer
PID 142393 exited due to signal 6
free(): invalid pointer
scripts/run_testdriver.sh line 68: 142392 Aborted

**Comment by xsacha** [comment]
There's a test in the validation script that ensures you fail when the config directory is missing.

It appears that you are failing to load your torch model, as you should, which will return an invalid pointer.

However, you have failed to verify that 1) the directory existed, 2) the model file existed and most importantly. 3) the model loaded. So when it comes time to clean up, you have attempted to free an invalid pointer.

**Comment by wfcb-85** [comment]
No, the config folder exists.
As mentioned in my original message, after I change my code and try no more to load the torch model (I set the null implementation as it originally was), the validation script keeps throwing the same error. With the same original code, it was compiling before.
I think there is a problem with the logs the validation script uses.

**Comment by xsacha** [comment]
"Checking for hard-coded config directory"
When this is printed, the script has renamed config to otherConfig

 free(): invalid pointer
When this is printed, your code has called free to a bogus pointer, observable in GDB. If you still can't see why this happens, look at the backtrace from GDB.

**Comment by wfcb-85** [comment]
Is not my code that has called free to a pointer.
I set the code back to a version that used to pass all the tests.

**Comment by xsacha** [comment]
You may go back to an older version where this test wasn't performed but I believe it won't be accepted.
Can you provide the backtrace?

**Comment by wfcb-85** [comment]
This is what I get when I build the original null Implementation:

Checking for hard-coded config directory free(): invalid pointer
PID 29153 exited due to signal 6
free(): invalid pointer
scripts/run_testdriver.sh: line 68: 29512 Aborted

**Comment by xsacha** [comment]
You'll need to run it with gdb, such as:
gdb --args myapp
You can add it to the script.
Then type 'b' and enter once it crashes.
This should show you which line it crashed on.

**Comment by wfcb-85** [comment]
Ok, I had to disable the fork() part of the main() of validate11.cpp in order to debug it entirely.
The error is coming from line 86:
auto ret = implPtr->createTemplate(faces, role, templ, eyes);

**Comment by wfcb-85** [comment]
The error persists even when I do nothing on the 'createTemplate' function and just return the Success status.

**Comment by wfcb-85** [comment]
Hello,
The problem is solved when I include the same libraries (Torch and Opencv) at the validate11 side, that I used for my implementation. I wonder, will that be a problem when NIST will evaluate my library?

**Comment by xsacha** [comment]
You mean you had used different versions of the libraries when running validate11? The correct libraries should be included in your implementation's lib/ path. It all gets zipped (lib, config, doc) for your submission.

**Comment by wfcb-85** [comment]
I linked those libraries statically and the problem is solved. Thank you.
