### ISSUE TITLE
Testing Limits

### ISSUE THREAD

**Issue by MdScntst** [usnistgov/frvt#50]
I've got that submission has to use 1 CPU thread. What are the other limits: inference time, RAM usage, etc?...

**Comment by mlngan** [comment]
The timing limits for 1:1 are listed in Table 1 of the API document: https://pages.nist.gov/frvt/api/FRVT_ongoing_11_api.pdf.

Please see the FRVT Evaluation Specifications for hardware specs: https://pages.nist.gov/frvt/api/FRVT_common.pdf.
