### ISSUE TITLE
Range of similarity 

### ISSUE THREAD

**Issue by cannguyen275** [usnistgov/frvt#52]
Hello,

According to the document, the similarity value is a similarity score resulting from comparison of the templates, **on the range [0,
1000000].**
We use cosine similarity to calculate the similarity score, the value is on the range [0,1].
Do we need to normalize that value from [0,1] to [0, 1000000]?

Thanks,

**Comment by paddygr** [comment]
No.  Any non-negative range is permitted eg. [0,1] or [300,400].


From: Kei ***@***.***>
Date: Tuesday, May 18, 2021 at 22:50
To: usnistgov/frvt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [usnistgov/frvt] Range of similarity (#52)

Hello,

According to the document, the similarity value is a similarity score resulting from comparison of the templates, on the range [0,
1000000].
We use cosine similarity to calculate the similarity score, the value is on the range [0,1].
Do we need to normalize that value from [0,1] to [0, 1000000]?

Thanks,
