### ISSUE TITLE
Script for FRVT 1:1 testing of multiface input 

### ISSUE THREAD

**Issue by GivralNguyen** [usnistgov/frvt#53]
Hi,
According to your documentations, a person can be represented by multiple images (and these images will be represented as a single std::vector<Image> . However your in your test scripts for FRVT 1:1, you only run test for one single enroll image - one verification image. Is there any way so we can test multiple enroll image - one/multiple verification image ?

**Comment by mlngan** [comment]
We've added a test case in the validation package for template generation using multiple image inputs.
