### ISSUE TITLE
Threshold to make the decision in FRVT 1:N package

### ISSUE THREAD

**Issue by manideep2510** [usnistgov/frvt#55]
In Table 10 on page 13 of [FRVT 1:N API document](https://pages.nist.gov/frvt/api/FRVT_ongoing_1N_api.pdf), we are asked to return a `decision` (true/false) whether there is a mate within the enrollment database for a query along with the candidate IDs and similarity score. What threshold should be used to make this decision in the [`identifyTemplate`](https://github.com/usnistgov/frvt/blob/master/1N/src/nullImpl/nullimplfrvt1N.cpp#L106) function?

On the [1:N leader board page](https://pages.nist.gov/frvt/html/frvt1N.html), it is told that `"threshold is set to limit to the False Positive Identification Rate (FPIR) to 0.003"` and also that `"The threshold is set for each algorithm and each column separately"`. So, we are assuming NIST would be setting the thresholds to get the final results.

So, we are confused on which threshold to use to make the decision in [`identifyTemplate`](https://github.com/usnistgov/frvt/blob/master/1N/src/nullImpl/nullimplfrvt1N.cpp#L106) function. Any help with this will be much appreciated.

Thanks in advance.

**Comment by mlngan** [comment]
The **decision** would a best guess.  You might apply a threshold, or you might do something else (for example, what if more than one person comes above threshold in a consolidated database?).  We'd use the **decision** to compute one point on a Detection Error Tradeoff (DET) curve.  It would probably lie on the DET we report (which sweeps across a number of different thresholds).

We're not going to use the **decision** for algorithm comparison.
