### ISSUE TITLE
Timing analysis

### ISSUE THREAD

**Issue by sam7177** [usnistgov/frvt#56]
Hello,

Do you use a separate script to perform timing analysis?
Would it be possible for you to share the code you use to test template creation time?
Thanks.

**Comment by mlngan** [comment]
We are basically doing the following (pseudocode):

start = std::chrono::system_clock::now()
createTemplate()
stop = std::chrono::system_clock::now()
time = stop - start

**Comment by sam7177** [comment]
@mlngan Thanks for the reply.
But does this code use any forking?
In your comment here https://github.com/usnistgov/frvt/issues/12#issuecomment-501275609 you mentioned "we lock all threads to using a single CPU".  Does this mean that the validation package is tested on a multi-cpu system, but only confined to single cpu via code?

**Comment by xsacha** [comment]
I'm sure they just set the process affinity using taskset or similar.
taskset - c $assignedcore ./testVendor

It is tested on one of the machines they list in the document. All are multiple core machines.
