### ISSUE TITLE
1:N submission - How to return templates when faces are not detected?

### ISSUE THREAD

**Issue by aravinthmuthu** [usnistgov/frvt#57]
In cases where faces are not detected by the detector, 
1) should we return an error code or a random template (feature vector, eye coordinates)? 
2) How will these templates be handled during enrolment, search phase?

**Comment by mlngan** [comment]
Per the API document (https://pages.nist.gov/frvt/api/FRVT_ongoing_1N_api.pdf):

For enrollment templates (TemplateRole=Enrollment_1N): When the implementation fails to produce a template (i.e. returns a non-successful return code), it shall still return a blank template (which can be zero bytes in length). The template will be included in the enrollment database/manifest like all other enrollment templates, but is not expected to contain any feature information.

For identification/probe templates (TemplateRole=Search_1N): If the function returns a non-successful return status, the output template will not be used in subsequent search operations.
