### ISSUE TITLE
What happens if the submission fails timing tests?

### ISSUE THREAD

**Issue by manideep2510** [usnistgov/frvt#58]
Hello,

If the package we submitted runs successfully without package/code/threads errors, but it does not pass the timing tests (Eg: Under 1500 ms for template creation in 1:1 package). Would we get a chance to fix the package and resend it immediately or would we have to wait for 4 calendar months?

If we can fix and resend the package immediately, will the submission be evaluated in the current iteration leaderboard update or the next update iteration?

Thanks in advance.

**Comment by mlngan** [comment]
If your submission fails timing, you will have one opportunity to resubmit immediately to resolve the timing issue.  We process submissions on a first-come-first-serve basis, so once we receive a working submission for you, we will run it and include it in the next report cycle.
