### ISSUE TITLE
Testing the final submission package

### ISSUE THREAD

**Issue by manideep2510** [usnistgov/frvt#59]
Hello

For example in 1:N package, upon successfully running `run_validate_1N.sh` script (in a fresh CentOS 8.2 system) without any error, it will create a submission package compressed in tar.gz format. How can we use this generated package to further test whether this submission package will run from NIST's side or not?

If we are able to prepare the submission package without any error, but during validation from NIST team, some errors pop up, how can we replicate these errors from our side? Before submitting the encrypted package, is there any script/command that we can use to test the validity of the submission package (the tar.gz file generated) like the NIST team would do?

Thanks in advance.

**Comment by mlngan** [comment]
If the validation script successfully ran and was able to generate the submission package, then that means it passed all preliminary validation checks, and you can just send us the encrypted tar.gz package to NIST.

If there are errors during validation on our end, we will notify you with the issues.
