### ISSUE TITLE
Fork return fail

### ISSUE THREAD

**Issue by svarjo** [usnistgov/frvt#6]
Hi, 

For some reason our current compilers fail to join at forked processes at validate11.cpp with return statement. It appears that using exit instead works. Any idea if this is an indication of some problem on our side or can this change be done safely?

Ie:
```
switch(fork()) {
		case 0: /* Child */
			if (action == Action::CreateTemplate)
				return createTemplate(
						implPtr,
						inputFile,
						outputDir + "/" + outputFileStem + ".log." + to_string(i),
						templatesDir,
						role);
			else if (action == Action::Match)
				return match(
						implPtr,
						inputFile,
						templatesDir,
                                                outputDir + "/" + outputFileStem + ".log." + to_string(i));
```
to 

```
switch(fork()) {
		case 0: /* Child */
			if (action == Action::CreateTemplate)
				exit( createTemplate(
						implPtr,
						inputFile,
						outputDir + "/" + outputFileStem + ".log." + to_string(i),
						templatesDir,
						role));
			else if (action == Action::Match)
				exit( match(
						implPtr,
						inputFile,
						templatesDir,
						outputDir + "/" + outputFileStem + ".log." + to_string(i)));
```

**Comment by xsacha** [comment]
I can confirm no such issue here.

My guess is that exit is avoiding the issue of running some destructors or killing some threads, which would be handled (and possibly fail) with the return method.

**Comment by quocnhat** [comment]
@svarjo how did you solve this problem? I got into the same as you are. child process does not return anything ( no bug) and that is why the whole process is suspended.

**Comment by svarjo** [comment]
If I recall right it was some release bug on our side of code. Maybe it is a good idea to verify memory usage with some tool such as AddressSanitizer or Valgrind.
