### ISSUE TITLE
Libarchive and cmake version mismatch   

### ISSUE THREAD

**Issue by sounak07** [usnistgov/frvt#60]
While running the scripts provided by NIST to compile and build the final package we are getting an error 

`cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd`

In order to resolve the issue we had to upgrade the libarchive to 3.3.3. Also, the issue was not seen with CMake version 3.17. 

Question: Is this issue been already resolved from NIST's end, since the repo is quite old and maybe has not been updated.

Should we go ahead with a version that works or it has to be the version in NIST's scripts install?

[Similar issue ](https://bugzilla.redhat.com/show_bug.cgi?id=1827927)

**Comment by mlngan** [comment]
Interesting.  We've never encountered this issue with cmake on our end.  Our systems are running CentOS Linux release 8.2.2004, cmake version 3.11.4, and libarchive.so.13.3.2.

**Comment by sounak07** [comment]
We are seeing this error with CMake version 3.18. So I think cmake 3.11.4 wont have issue, we can submit the package.

**Comment by mlngan** [comment]
I just did a fresh install of the CentOS 8.2 image on a VM and the latest cmake package being pulled from AppStream is indeed version 3.18.2-11.  I was able to replicate your issue with libarchive, so I've added the libarchive package to the installation list in the validation scripts (which should pull the correct/compatible version).

**Comment by cannguyen275** [comment]
I've just fresh install the CentOS 8.2 on VM, and even the new commit has added libarchive but the issue is still.
It seems that libarchive 3.3.2 is already installed in my fresh installed CentOS. I solved it by update libarchive to 3.3.3 using:
`sudo yum update libarchive`

**Comment by mlngan** [comment]
Thanks for making us aware of this.  We have added the libarchive update to the validation scripts.
