### ISSUE TITLE
Resolution constraints for the input image?

### ISSUE THREAD

**Issue by sparupat** [usnistgov/frvt#63]
What is the minimum and maximum resolution of input image to createTemplate method  or is it 640x480? 

createTemplate(
const Multiface &faces,
TemplateRole role, Input
std::vector<uint8_t> &templ,
std::vector<EyePair> &eyeCoordinates);

**Comment by mlngan** [comment]
There is no minimum/maximum resolution per se.  In our report and on our leaderboard under the resources tab, you'll see that we run on images as large as 3000x4500, sometimes larger.  If your software inherently does not support certain image sizes, it should fail gracefully, meaning return a successful return code and encode the failure within your template.  It should not crash.
