### ISSUE TITLE
Thread count

### ISSUE THREAD

**Issue by avinashkshirsagar** [usnistgov/frvt#64]
I have limited thread of Tensorflow and Pytorch to 1, but still the warning message mentions about detecting 6 threads. Out of these 6 threads only one thread is running and others are in sleep mode. The following is the output of htop command for the above mentioned scenario. In one of the comment it is mentioned that you check multithreading case by case, Is this case acceptable for submission?
![Screenshot (537) - Copy](https://user-images.githubusercontent.com/25266500/133846525-ad5b2849-f2e9-4389-b67e-1a6f4b5ad2ea.png)

**Comment by mlngan** [comment]
We are only interested in the active threads, so given you only have a single active thread, it should be fine.  Send us your submission, and we will validate the active thread count on our end.  Thanks.
