### ISSUE TITLE
ubuntu 20.04.3 LTS evaluation gcc version

### ISSUE THREAD

**Issue by slpal** [usnistgov/frvt#66]
Should gcc version be 9.3 (ubuntu 20.04.3 LTS default) or 8.3.1 as usual, when switching the FRVT evaluation operating system to Ubuntu 20.04.3 LTS?
Thx

**Comment by xsacha** [comment]
I used gcc 11 with CentOS on previous submissions.
Ubuntu 20.04 comes with gcc-10 in the standard repo by the way.

The version of gcc is unlikely to be the matter but rather the version of glibc, which any compiler on Ubuntu 20.04 should use.

**Comment by mlngan** [comment]
Our Ubuntu image is running g++ version 9.3.0.
