### ISSUE TITLE
Does the implementation of FRVT 1:N search also need to be limited to a single process？ 

### ISSUE THREAD

**Issue by powermano** [usnistgov/frvt#68]
As shown in the following picture, you need to test the speed of 1:N search with one single-core, but in the run_testdriver.sh script, only the number of processes during createTemplate is counted, but not during 1;N search.  Does the implementation of FRVT 1:N search also need to be limited to a single process？ 

![image](https://user-images.githubusercontent.com/24365567/153814230-b302548e-8708-41fa-9f0e-649698e14b63.png)

**Comment by mlngan** [comment]
Yes, the implementation of 1:N search needs to be limited to a single process.
