### ISSUE TITLE
Tensorflow is not fork safe

### ISSUE THREAD

**Issue by FranciscoSierra27** [usnistgov/frvt#69]
Hi NIST team.

I've created a dynamic library from Rust that my implementation of "frvt.h" in c++ uses, but I have a problem.
My model inference is made with TensorFlow, when I run the "run_validate.sh". It hangs indefinitely.
I've read that TF is not fork safe so that might be the problem. 

¿Do you suggest to try another Machine Learning framekork or is there a workaround for this issue?

Edit: added a missing word "framework".

**Comment by xsacha** [comment]
All the main frameworks such as tensorflow, pytorch and mxnet have been known to work in NIST.
You may just need to compile it differently or set it up (usually a setting in each framework) so it does not attempt to use multi-threading.

**Comment by FranciscoSierra27** [comment]
Okay, I'll see if it is a multi thread problem and if I can recompile it without multi-threading.

**Comment by FranciscoSierra27** [comment]
Hi NIST team.
I've searching a lot and sadly, I've had the same problem. 
I even migrated my TF Rust code to CPP with no luck.

Researching a little more I foud an open issue regarding NIST implementatinos in the official TF github and they say as follows:
[https://github.com/tensorflow/tensorflow/issues/51832#issuecomment-926205545
](url)
So basically NIST API is not compatible with all model inferences with TF and the TF developers have not intenssions to make TF fork safe.

¿Do you have any plans to make more compatible your API with TF?
For me it's contradictory that you use forks when TF, one of the more spreaded IA framekors, is not fork safe.

I've seen that TF allows "sessions" as servers, and "session-clients". But that will require an extra process to use it. I assume that that implementation is not allowed by NIST.

**Comment by mlngan** [comment]
We've received a number of submissions using TF.  It's possible to move your model initialization to the child process (after the fork) and invoke it once during the first API call.  As for measuring timing, we consider and report the median time across thousands of API calls (e.g. createTemplate()), so even if your very first API function invocation takes longer, it should not impact the timing benchmark.

**Comment by FranciscoSierra27** [comment]
Thanks. That was my first approach, but TF in Rust takes a long time to initialize. In c++ the initialization is faster.
Now  I'm initializing at "matchTemplate" once per fork.

Just as conclussion for this issue. If you initialize your TF model at "initialize()", you should try to initialize it once per fork at "matchTemplate" or "createTemplate". Regarding the time, it may not affect considerably the benchmark due the mean calculatiuon of thousands of API calls.

¿Am I right?

**Comment by alvinwong64** [comment]
> We've received a number of submissions using TF. It's possible to move your model initialization to the child process (after the fork) and invoke it once during the first API call. As for measuring timing, we consider and report the median time across thousands of API calls (e.g. createTemplate()), so even if your very first API function invocation takes longer, it should not impact the timing benchmark.

@mlngan Hi do you mean that I only load my tensorflow model at creating the templete( createFaceTemplate) would be a workaround? Since loading the model at initialize will causes deadlock.
