### ISSUE TITLE
match against failed templates

### ISSUE THREAD

**Issue by mtamburrano** [usnistgov/frvt#70]
Hi,

for frvt_11, I read in th documentation of the template creation:
```
In all cases, even when unable to extract features, the output shall be a template that may be
passed to the matchTemplates() function without error. That is, this routine must internally encode "template
creation failed" and the matcher must transparently handle this.
```

Fine, but what about similarity?
Evene if I return some error during template creation step, that template is still being passed to `matchTemplates` and returning a similarity makes no sense.
The failed templates shouldn't be supposed to not being passed to match functions? If not, what similarity should I return in those cases?

Thanks

**Comment by mlngan** [comment]
You can set the similarity score to whatever value you think is a good idea, for example, returning a very low score to represent a rejection or setting the similarity score to -1.0.
