### ISSUE TITLE
If my code needs to read the model externally, where should I put the face recognition related models ？

### ISSUE THREAD

**Issue by powermano** [usnistgov/frvt#71]
Take 1:N as an example. In the NullImplFRVT1N::initializeTemplateCreation  func,  I  should load the face recognition related models. If puting the face recognition related models in the same level directory as run_validate_1N.sh,  may i use './face_model' in the initializeTemplateCreation function?

```
NullImplFRVT1N::initializeTemplateCreation(
    const std::string &configDir,
    FRVT::TemplateRole role)
{
    face_model model = load('./face_model');
    return ReturnStatus(ReturnCode::Success);
}
```
the following is the tree struct of 1N directory. 
|-- CMakeLists.txt
|-- README.md
|-- bin
|   `-- validate1N

|-- config
|-- doc
|   `-- version.txt

|-- input
|   |-- enroll_1N.txt
|   |-- enroll_1N_multiface.txt
|   |-- enroll_1N_short.txt
|   |-- insert.txt
|   |-- search_1N.txt
|   `-- search_1N_multiperson.txt

|-- lib
|   `-- libfrvt_1N_xxx_000.so

|-- libfrvt_1N_xxx_000.tar.gz
|-- run_validate_1N.sh
|-- scripts
|   |-- build_null_impl.sh
|   |-- compile_and_link.sh
|   `-- run_testdriver.sh

`-- validation

**Comment by xsacha** [comment]
The models should be located in the 'config' directory.

**Comment by powermano** [comment]
> The models should be located in the 'config' directory.
> 
> I don't think there's any guarantee over the other directories which is why the configDir is supplied in the function.

thanks.
