### ISSUE TITLE
Error Detection of hard-coded config directory  when run ./run_validate_11.sh 

### ISSUE THREAD

**Issue by jatsi** [usnistgov/frvt#76]
Running ./run_validate_11.sh shows me the following error:

**Checking installation of required packages [SUCCESS]
Looking for core implementation library in /home/daksha/Documentos/frvt/11/lib.[SUCCESS] Found core implementation library /home/daksha/Documentos/frvt/11/lib/libfrvt_11_facedaksha_000.so.
Attempting to compile and link /home/daksha/Documentos/frvt/11/lib/libfrvt_11_facedaksha_000.so against test harness.
Scanning dependencies of target validate11
[ 33%] Building CXX object src/testdriver/CMakeFiles/validate11.dir/home/daksha/Documentos/frvt/common/src/util/util.cpp.o
[ 66%] Building CXX object src/testdriver/CMakeFiles/validate11.dir/validate11.cpp.o
[100%] Linking CXX executable ../../../bin/validate11
[100%] Built target validate11
[SUCCESS] Built executable in /home/daksha/Documentos/frvt/11/bin.
------------------------------
 Running 1:1 validation
------------------------------**
Checking for hard-coded config directory PID 52211 exited due to signal 11
[ERROR] Detection of hard-coded config directory in your software.  Please fix!

I do not hard-coded config in source code, create config folder for my models.

**Comment by vuvko** [comment]
Your program threw a Segmentation Fault error (signal 11). The `run_validate_11.sh` script just checks whether the programs return a successful exit code 0.

**Comment by jatsi** [comment]
thanks

**Comment by jaisanant0** [comment]
@jatsi  did you solve it?
