### ISSUE TITLE
[Error] Enrollment validation (multi person in image) failed - when no face detected

### ISSUE THREAD

**Issue by dzeus14omega** [usnistgov/frvt#77]
on function createMultiTemplates() in validate11.cpp, i found that it requires "the output template vector must contain at least one template"; but in some situations, model face-detector cannot detect anything for example, we don't return any templates and that cause this error. 
So can anyone help me what i should return at this case or any solution to solve this problem?

**Comment by mlngan** [comment]
Per the [FRVT 1:1 API](https://pages.nist.gov/frvt/api/FRVT_ongoing_11_api.pdf), if the implementation is unable to extract features, the output shall still contain a single template that may be passed to the matchTemplates() function without error. That is, this routine must internally encode "template creation failed", and the matcher must transparently handle this.  A template may have length zero bytes as long as your matcher handles it.
