### ISSUE TITLE
Query on time limit during testing for 1-1

### ISSUE THREAD

**Issue by tanpengshi** [usnistgov/frvt#78]
I am embedding my Python codes in C++.

My concern is regarding the time taken for each image inference, because I understand the time limit for image enrollment is 1500ms. Using this code above i take about 2.5seconds to 3 seconds (on Virtual Machine CPU) to iterate between each std::cout during runtime, as shown:

![image](https://user-images.githubusercontent.com/24505990/198968574-729f0fd2-7a62-49cc-99b2-10f1eba88921.png)

However, during testing with Python on my CPU work station, each template generation only takes about 190ms, as shown:

![image](https://user-images.githubusercontent.com/24505990/198969045-7465677d-b70b-4ecb-88a6-771f37c03dcc.png)

My question is how are the codes being tested for timings, and would my codes potentially exceed the time limit? Appreciate the help!

**Comment by xsacha** [comment]
It is 1.5 second per feature generation (detection + recognition) on a single core of the CPUs specified in the API document.

In your Python example, it is running multi-threaded and looks like you are only doing face recognition on a 112x112 image, which is a far easier task.
