### ISSUE TITLE
Can you provide minimal docker image?

### ISSUE THREAD

**Issue by shubhamwagh** [usnistgov/frvt#80]
Hi, it will be great if you can provide minimal docker image for running validation scripts. Thanks.

**Comment by 4sfaloth** [comment]
The base image seems to be the same you get from the official ubuntu repo for 20.04.3, so I think it should be okay to use a corresponding base dockerfile such as `ubuntu:focal-20220113`. Still would be preferable to have an official response from NIST for sure 🤞

**Comment by mlngan** [comment]
Per the our published documentation, the operating system that the submitted implementations shall run on is released as a downloadable file accessible from https://nigos.nist.gov/evaluations/ubuntu-20.04.3-live-server-amd64.iso, which indeed is the 64-bit version of Ubuntu 20.04.3 LTS (Focal Fossa).

**Comment by seba-eng** [comment]
This is an older issue but I think it is still relevant. Using an iso file is much less convenient than using a docker image in CI/CD systems like jenkins, that are frequently used to automatically build and test releases. 
Given that it the OS requirement is quite specific and not the most recent LTS release of Ubuntu 20, it is quite hard to find something that works.

**Comment by deeperlearner** [comment]
I use [this](https://hub.docker.com/r/swathip2021/myubuntu) image in the first line of my Dockerfile.
```
FROM swathip2021/myubuntu:20.04 AS ubuntu
```
