### ISSUE TITLE
how to pass an array of array from python to C++ (multiple faces in an image) 

### ISSUE THREAD

**Issue by tanpengshi** [usnistgov/frvt#81]
I am doing template generation for multiple faces in image:

I am returning an array of array (array of templates) from python to c++. Here is a snippet of my codes:

```
npy_intp dims[3] = {height,width,channel};
np_arg = reinterpret_cast<PyArrayObject*>(PyArray_SimpleNewFromData(3,dims,NPY_UINT8,image.data.get()));
pArgs = PyTuple_New(1);
PyTuple_SetItem(pArgs, 0, reinterpret_cast<PyObject*>(np_arg));
pValue = PyObject_CallObject(pFunc, pArgs);
if  (pValue==nullptr){
        PyErr_Print();
}
np_ret = reinterpret_cast<PyArrayObject*>(pValue);
c_out = reinterpret_cast<float**>(PyArray_DATA(np_ret));
std::cout << c_out[0][0] << std::endl;
```

During runtime, i encounter segmentation error at std::cout << c_out[0][0] << std::endl; (PID 8132 exited due to signal 11)
std::cout << c_out[0] << std::endl; runs fine though.

What did I do wrong?

**Comment by xsacha** [comment]
If you dereference the pointer and there's nothing there, it'll crash. That appears to be the case.
For example, if c_out[0] is nullptr (0), what do you expect?
