### ISSUE TITLE
Pose Orientation at Test Time FRVT 1-1

### ISSUE THREAD

**Issue by tanpengshi** [usnistgov/frvt#85]
In validation package, some images are orientated 90 degrees from the front, as such sometimes we are comparing frontal faces against side faces OR side faces against side faces.

May I know would similar facial orientation (frontal against side OR side against side) be used during testing and evaluation by NIST?

**Comment by mlngan** [comment]
Some of our unconstrained, non-cooperative datasets can contain images with large pose variations.
