### ISSUE TITLE
run_validation_11 not found

### ISSUE THREAD

**Issue by thuanbvv** [usnistgov/frvt#89]
Hi

I don't see any file with name run_validation_11.sh like README.md in 11.
Please review that.

Thanks,

**Comment by RomainCendre** [comment]
Humm? I'm not from the NIST but on the master branch you have the file you're looking for : https://github.com/usnistgov/frvt/blob/master/11/run_validate_11.sh
Best regards

**Comment by mlngan** [comment]
There was a typo in the README.md file.  We've fixed the name of the script.
