### ISSUE TITLE
Pad track: evasion

### ISSUE THREAD

**Issue by mlourencoeb** [usnistgov/frvt#91]
Dear @mlngan 

I am writing to ask if there is mandatory to implement evasion for the new pad challenge. If case it is optional, should we return not implemented error status to not be considered for that track?

Best,
/m

**Comment by mlngan** [comment]
Per the API and evaluation plan, it is not required to implement both PAD functions.  For the function that you choose not to implement, please return ReturnCode::NotImplemented.

**Comment by mlourencoeb** [comment]
Thanks for the quick reply. In that case, I believe that the algorithm is not even considered for the other evaluation type, right? 
Best,
/m

**Comment by mlngan** [comment]
That is correct.
