### ISSUE TITLE
There are two questions about whether the templateID will be duplicated in the input folder in the 1:N test

### ISSUE THREAD

**Issue by yyfrzx** [usnistgov/frvt#93]
Hi,
We are preparing a NIST 1:N submission and are facing some issues:
1. Will the templateID of the enroll_1N_multiface.txt under the input folder be duplicated in the real test?
    For example:
    It currently looks like this:
    1 .. /common/images/S001-01-t10_01.ppm UNKNOWN .. /common/images/S001-03-t10_01.ppm UNKNOWN .. /common/images/S001-05-t10_01.ppm UNKNOWN 
    21 .. /common/images/S008-02-t10_01.ppm UNKNOWN .. /common/images/S008-04-t10_01.ppm UNKNOWN .. /common/images/S008-06-t10_01.ppm
    45 .. /common/images/S023-01-t10_01.ppm UNKNOWN .. /common/images/S023-03-t10_01.ppm UNKNOWN

    Will this happen？:
    1 .. /common/images/S001-01-t10_01.ppm UNKNOWN .. /common/images/S001-03-t10_01.ppm UNKNOWN .. /common/images/S001-05-t10_01.ppm UNKNOWN 
   21 .. /common/images/S008-02-t10_01.ppm UNKNOWN .. /common/images/S008-04-t10_01.ppm UNKNOWN .. /common/images/S008-06-t10_01.ppm
   21 .. /common/images/S001-07-t10_01.ppm UNKNOWN .. /common/images/S001-08-t10_02.ppm UNKNOWN .. /common/images/S001-09-t10_01.ppm UNKNOWN
   45 .. /common/images/S023-01-t10_01.ppm UNKNOWN .. /common/images/S023-03-t10_01.ppm UNKNOWN

2. Will the templateID in the insert.txt under the input folder coincide with the templateID in the enroll_1N.txt?

Thank you.
Looking forward to your reply.

**Comment by yyfrzx** [comment]
Thanks for your quick reply！

**Comment by Leila132** [comment]
@mlngan Hello! I thought it would be appropriate to ask this question here. Does the statement "The enrollment template IDs will always be unique" mean that there cannot be duplicate template IDs in the manifest file, as described in section 7.1 of the document here -- https://pages.nist.gov/frvt/api/FRVT_IREX_ongoing_1N_api.pdf (example file -- Table 2)? In other words, does this imply that when implementing the Search (S4) function, there is no need to worry about duplicate template IDs or filter them based on any criteria (e.g., keeping only one occurrence of a duplicate template ID with the highest score in the candidate list)?

Additionally, for better understanding -- do the templates that we return in the functions create{Face,Iris,FaceAndIris}Template(TemplateRole=Enrollment_1N) "under the hood" acquire some template IDs, which are then included in the manifest file (from section 7.1)? Or am I misunderstanding something about this process?

**Comment by mlngan** [comment]
Yes, all template IDs in the gallery will be unique - no need to worry about duplicate template IDs.

Each template that is created will be associated with a unique template ID that gets stored in the manifest file.
